export const ACTIONS = {
    ADD_QUESTION: "ADD_QUESTION",
    RECEIVE_USERS: "RECEIVE_USERS",
    RECEIVE_QUESTIONS: "RECEIVE_QUESTIONS",
    SET_AUTHED_USER: "SET_AUTHED_USER",
    SUBMIT_ANSWER: "SUBMIT_ANSWER"
}